Feature/specification
doonutmate/doonut-server pull request #1
Opened 2023-10-21 10:10 UTC by jickDo

* 변경점

Gradle 32~34 Line - 현재 spring fox swagger 의경우 20.07년 기준 업데이트가 멈춰있는 상태여서 spring doc swagger로 의존성을 주입하였습니다.

ExampleController 19, 25~32 Line - Example 전체 tag 설정, create api 명세설정, (200, 400, 404 http status code 반응 설정) 
ApiResponse 부분은 작성하는 것이 맞는지 검토 부탁 드립니다.

ExampleCreateReq 3~9 Line - Dto 명세, name 속성값 명세

yml 21 ~ 31 Line-  스웨거 설정에서 오류 발생 때문에 ant-path-matcher로 변경, swagger 기본 주소를 localhost:8080/api로도 가능하게 설정, api 정렬방식을 알파벳 순으로 변경

** 명세를 진행하면서 어디까지 명세를 해야 한다는 기준이 없어서, 그 부분에 대해 질문을 드리고 싶습니다!!

2023-10-21 13:28 UTC, yeongunheo requested changes
지금은 API가 한번에 모두 나오고 있는데, 나중에 Example 외 도메인이 추가되면 도메인 별로 페이지를 따로 보는 게 필요할 것 같아요.  
아래 [데모 페이지](https://demos.springdoc.org/demo-spring-boot-3-webmvc/swagger-ui/index.html?urls.primaryName=users) 오른쪽 상단처럼 그룹화를 해주실 수 있을까요?  

<img width="1449" alt="스크린샷 2023-10-21 오후 10 25 52" src="https://github.com/doonutmate/doonut-server/assets/52141636/431df0ab-519b-4c06-b342-1bbab9038330">.  
  
  
참고 : https://springdoc.org/#how-can-i-define-multiple-openapi-definitions-in-one-spring-boot-project

2023-10-21 13:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/dto/ExampleCreateReq.kt
> +@Schema(description = "example 생성용 DTO")
`@Schema(title = "example 생성용 DTO")`과 어떤 차이가 있나요?  
description과 title 중 어떤 걸 사용하는게 다른 사람이 보기 편할까요?

2023-10-21 13:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/dto/ExampleCreateReq.kt
> +    @Schema(description = "이름")
여기에서도 title과 description 중 어떤 걸 사용하는게 더 좋을까요?

2023-10-21 13:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/ExampleController.kt
> +            ApiResponse(responseCode = "200", description = "성공", content = [(Content(mediaType = "application/json", array = (ArraySchema(schema = Schema(implementation = ExampleCreateReq::class))))
실제로 api 응답값이 아무것도 없는데 문서 상으로 return값이 `ExampleCreateReq`인 것처럼 표시한다면 헷갈릴 것 같아요!

2023-10-21 13:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/ExampleController.kt
> +            ApiResponse(responseCode = "404", description = "Not Found", content = [Content()]),
매번 400, 404 ApiResponse를 표시하는게 좋을까요?

2023-10-21 13:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/ExampleController.kt
>      fun create(@RequestBody req: ExampleCreateReq) {
이건 취향차이긴 한데 전 `@PostMapping` 같은 애노테이션은 메서드에 최대한 붙여놓고, `@Operation`, `@ApiResponses` 같은 문서화에 필요한 애노테이션은 메서드에 멀리 떨어져놓는 편이에요. 문서화 툴은 나중에 바뀔 수도 있고, 비즈니스로직에 직접적으로 영향을 주지 않기 때문입니다.

```suggestion
    @Operation(summary = "테스트용 API", description = "=====API 설명=====")
    @ApiResponses(
        value = [
            ApiResponse(responseCode = "200", description = "성공", content = [(Content(mediaType = "application/json", array = (ArraySchema(schema = Schema(implementation = ExampleCreateReq::class)))))]),
            ApiResponse(responseCode = "400", description = "Bad Request", content = [Content()]),
            ApiResponse(responseCode = "404", description = "Not Found", content = [Content()]),
        ],
    )
    @PostMapping
    fun create(@RequestBody req: ExampleCreateReq) {
```

2023-10-21 13:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/ExampleController.kt
<img width="424" alt="image" src="https://github.com/doonutmate/doonut-server/assets/52141636/f3e2e901-8325-40f4-a623-80b736dcacf9">.  

현재 이렇게 표시되고 있는데요,  
- OpenAPI definition을 doonut-app-exteranl-api로,
- v0을 v1.0으로  
  
바꿔주실 수 있을까요?

2023-10-21 13:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/ExampleController.kt
> +    @Operation(summary = "테스트용 API", description = "=====API 설명=====")
summary를 `Example 생성`으로 바꾸고 ExampleController.get() 조회용 API를 추가해서 `Example 조회` 문서화도 만들어두는건 어떨까요?

2023-10-21 13:52 UTC, yeongunheo commented on doonut-app-external-api/src/main/resources/application.yml
> +      matching-strategy: ant_path_matcher
제 로컬에선 이 부분 주석처리하고 띄우면 정상적으로 띄워지던데, 직찬님 로컬에서는 띄울 때 에러가 발생하나요?

2023-10-21 14:08 UTC, oereo reviewed
살짝 리뷰 달아놓았습니다!
영운님께서 리뷰를 잘 달아주셨고 저도 공감하는 리뷰가 많아서 그 외의 리뷰를 달 만한 부분을 찾아서 적어놓았습니다!

2023-10-21 14:08 UTC, oereo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/ExampleController.kt
>      fun create(@RequestBody req: ExampleCreateReq) {
저도 이 부분 동의합니다!

2023-10-21 14:08 UTC, oereo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/dto/ExampleCreateReq.kt
> +    @Schema(description = "이름")
저는 개인적으로 swagger를 사용할 때 field에 붙이는 `@Schema` annotation에 example도 작성하는 편이에요!
사실 description을 정말 자세하게 작성해주면 좋긴하지만 보통은 field를 한글 단어로 직역하는 것이 대부분인 것 같아서 테스트할 때 example 같은 예시 데이터가 있으면 좋을 것 같아요!

2023-10-21 14:08 UTC, oereo commented on doonut-app-external-api/src/main/resources/application.yml
>    port: 8081
이건 별건 아니지만... endline만 살짝 신경써주시면 감사하겠습니다!

2023-10-21 14:30 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/dto/ExampleCreateReq.kt
> +    @Schema(description = "이름")
저도 example을 붙이는 걸 선호합니다! 그럼 여기도 example 붙이는 걸로 가시죠!  
```suggestion
    @Schema(description = "이름", example = "jichan")
```

2023-10-21 14:34 UTC, yeongunheo commented on doonut-app-external-api/src/main/resources/application.yml
>    port: 8081
파일 끝에 newline 추가하는 것 말씀이신가요? 다같이 인텔리제이 세팅에 추가해도 좋을 것 같네요 :)
- https://jojoldu.tistory.com/673

2023-10-21 15:08 UTC, oereo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/dto/ExampleCreateReq.kt
> +    @Schema(description = "이름")
좋습니다!!

2023-10-21 15:09 UTC, oereo commented on doonut-app-external-api/src/main/resources/application.yml
>    port: 8081
오오 맞아요!!! 좋습니다!!

2023-10-22 04:44 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/dto/ExampleCreateReq.kt
> +@Schema(description = "example 생성용 DTO")
@Schema(descrition="~") 보다는 @Schema(title="~")이 가독성면에서 좋은것 같습니다.

스키마가 접혀있을때 title 내용이 표시 되어 안에 들어있는 내용을 유추할 수 있다는 점, 스키마를 폈을때는 description은 example보다 뒤쪽에 위치하여 주어진 조건을 확인 못한 상태에서 example을 보게 된다는 점이 다른 분들이 불편함을 겪을 것이라 생각하였습니다.

2023-10-22 04:45 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/ExampleController.kt
> +            ApiResponse(responseCode = "200", description = "성공", content = [(Content(mediaType = "application/json", array = (ArraySchema(schema = Schema(implementation = ExampleCreateReq::class))))
이부분은 제가 코드에 대한 이해가 부족했습니다. 좋은 피드백 감사드립니다!

2023-10-22 04:46 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/ExampleController.kt
> +            ApiResponse(responseCode = "404", description = "Not Found", content = [Content()]),
의미 없이 중복된 부분이 생겨난것 같습니다. 이부분은 지워두겠습니다!

2023-10-22 04:53 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/ExampleController.kt
>      fun create(@RequestBody req: ExampleCreateReq) {
어노테이션 위치에 관한 부분은 고민을 하지 않고 익숙한대로 작성해왔었는데, 스웨거 어노테이션 처럼 직접적으로 비즈니스 로직에 영향을 주지 않는 코드는 멀리 떨어트려 놓는게 맞다는 생각이 듭니다. `@Operation` 이나 `'@ApiResponses`처럼 어는 정도 크기가 있는 어노테이션은 비즈니스 로직 근처에 붙여두니 코드의 가독성을 해치는것 같다는 생각을 하였습니다!!

2023-10-22 04:53 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/ExampleController.kt
넵 변경하겠습니다!

2023-10-22 04:54 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/ExampleController.kt
> +    @Operation(summary = "테스트용 API", description = "=====API 설명=====")
summary를 변경후, 조회용 API를 생성하겠습니다!!

2023-10-22 04:58 UTC, jickDo commented on doonut-app-external-api/src/main/resources/application.yml
> +      matching-strategy: ant_path_matcher
제 로컬에서도 에러는 발생하지 않습니다. 레퍼런스들 참고하면서 오류가 발생할 수도 있다는 글들을 참고하여 넣어두었습니다. 이 부분은 제가 확인을 하고 진행하여야 했는데 생각이 짧았습니다….

2023-10-22 04:59 UTC, jickDo commented on doonut-app-external-api/src/main/resources/application.yml
>    port: 8081
넵 좋습니다!!

2023-10-22 06:38 UTC, Tarakyu approved these changes
좋네요 허허
코틀린 공부가 되네요

2023-10-22 06:38 UTC, Tarakyu commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/ExampleController.kt
>      @Autowired var exampleAppservice: ExampleAppService,
이번 직찬님 커밋이랑은 상관 없긴 한데..
`exampleAppservice` 대소문자 잘못된 거 같아용 ㅋㅋ 
별 거 아니니 지금 고치셔도 되고 나중에 고치셔도 되고.. 사실 냅둬도 되고..

2023-10-22 08:31 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/controller/dto/ExampleCreateReq.kt
> +@Schema(description = "example 생성용 DTO")
저도 불필요한 클릭 수를 줄여준다는 점에서 description 보다 title을 선호하는 편이에요!

2023-10-22 08:38 UTC, yeongunheo approved these changes
고생하셨습니다! 코멘트 몇개 추가로 남겨두었는데 확인 부탁드려요!

2023-10-22 08:38 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/service/ExampleAppService.kt
> +        exampleBusinessService.get(exampleId)
조회 메서드니까 return이 필요할 것 같아요!

2023-10-22 08:38 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/SwaggerConfig.kt
> +    }
example에 종속된 설정이니 example.config 패키지 내에 선언해도 좋을 것 같아요

2023-10-22 08:48 UTC, oereo approved these changes
고생하셨습니다!

2023-10-22 11:38 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/example/service/ExampleAppService.kt
> +        exampleBusinessService.get(exampleId)
메서드에 return 추가 하였고 반환타입 Example로 지정해두었습니다!!

2023-10-22 11:39 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/SwaggerConfig.kt
> +    }
example 패키지 아래 configuration 패키지 만들고 그 안에 example.config 안에 옮겨두었습니다!!

2023-10-22 11:43 UTC, jickDo commented
피드백 해주셔서 감사합니다 :)

2023-10-22 11:46 UTC, merged