Feature/jickchan/apple oauth
doonutmate/doonut-server pull request #36
Opened 2024-03-10 08:09 UTC by jickDo

2024-03-14 12:37 UTC, yeongunheo requested changes
전략패턴 써주셨길래, when 분기문 없애는 것에 대한 리뷰 몇개 남겼습니다!  
참고 : https://ohzzi.io/strategy-pattern/

2024-03-14 12:37 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/service/strategy/StrategyMemberDelete.kt
> +interface StrategyMemberDelete {
[Kotline Coding converntions](https://kotlinlang.org/docs/coding-conventions.html#choose-good-names)에 맞춰 클래스명은 명사 또는 명사구로 짓는게 좋을 것 같습니다.

> The name of a class is usually a noun or a noun phrase explaining what the class is: List, PersonReader.
```suggestion
interface MemberDeleteStrategy {
```

2024-03-14 12:37 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/service/MemberAppService.kt
> +            }
스프링 DI와 다형성을 이용하면 분기문을 없앨 수 있습니다!

```suggestion
    private val deleteStrategies: List<MemberDeleteStrategy>,
    private val memberBusinessService: MemberBusinessService,
) {
    fun delete(req: DeleteRequest) {
        deleteStrategies.first { it.supports(req.oauthType) }
            .delete(req)
    }
```

2024-03-14 12:37 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/service/strategy/StrategyMemberDelete.kt
> +    fun delete(req: DeleteRequest)
분기문을 없애기 위한 supports 메서드가 필요할 것 같아요.

```suggestion
    fun supports(oauthType: OauthType): Boolean
    fun delete(req: DeleteRequest)
```

2024-03-14 12:37 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/service/strategy/AppleMemberDelete.kt
> +    }
메서드 추가해줍시다!
```suggestion
    }
    override fun supports(oauthType: OauthType): Boolean {
        return OauthType.APPLE == oauthType
    }
```

2024-03-14 12:37 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/service/strategy/KakaoMemeberDelete.kt
> +    }
메서드 추가해줍시다!
```suggestion
    }
    override fun supports(oauthType: OauthType): Boolean {
        return OauthType.KAKAO == oauthType
    }
```

2024-03-14 12:37 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/apple/client/AppleAccessClient.kt
> +    fun reissuanceAccessTokens(
[Kotline Coding converntions](https://kotlinlang.org/docs/coding-conventions.html#choose-good-names)에 맞춰 메서드명은 동사로 짓는게 좋을 것 같습니다.
> The name of a method is usually a verb or a verb phrase saying what the method does: close, readPersons. 
```suggestion
    fun reissueAccessTokens(
```

2024-03-14 12:37 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/apple/service/AppleOauthProvider.kt
> +        return claims
```suggestion
        return appleJwtParser.parsePublicKeyAndGetClaims(loginRequest.accessToken, publicKey)
```

2024-03-15 03:35 UTC, yeongunheo commented on doonut-app-external-api/build.gradle.kts
> +//        into("src/main/resources")
이거 주석 다시 원복해주세요!

2024-03-15 13:46 UTC, yeongunheo approved these changes
고생하셨습니다! 잘 작동하는 코드이기에, 개선하면 좋을 포인트만 몇가지 남겼습니다!  
그리고 머지 전에 `origin/develop` 브랜치 pull을 받아야할 것 같아요!

2024-03-15 13:46 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/service/strategy/MemberDeleteStrategy.kt
> +    fun supports(oauthTypeStrategy: OauthTypeStrategy): Boolean
List가 아닌 Map을 활용한다면 supports 메서드는 다시 없애도 될 것 같아요.  
```suggestion

```

2024-03-15 13:46 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/controller/MemberController.kt
> +        @RequestParam oauthTypeStrategy: OauthTypeStrategy,
API를 사용하는 클라이언트는 내부 구현에서 전략 패턴을 사용하는지 드러낼 필요가 없을 것 같아요.  
내부 구현은 언제든 변경될 수 있으니 oauthType으로 이름을 변경하는게 좋을 것 같습니다!  

```suggestion
        @RequestParam oauthType: OauthType,
```

2024-03-15 13:46 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/member/model/OauthTypeStrategy.java
> +    APPLE("appleMemberDelete");
`KakaoMemberDelete.kt`, `AppleMemberDelete.kt` 클래스명이 바뀐다면 여기도 변경해줘야하는데, 이건 런타임 에러 때 발견가능해서 언제든 터질지 모르는 시한폭탄인 것 같아요.  

인터페이스에 추상 프로퍼티를 만들어서 개선해볼까요?  

```suggestion
public enum OauthTypeStrategy {
    val oauthType: OauthType
```

2024-03-15 13:46 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/member/model/OauthTypeStrategy.java
> +    APPLE("appleMemberDelete");
OauthType하고 OauthTypeStrategy을 하나로 합칠 수 있지 않을까요?

2024-03-15 13:46 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/service/strategy/KakaoMemeberDelete.kt
클래스명에 오타가 있는 것 같아요!

2024-03-15 23:00 UTC, jickDo commented on doonut-core/src/main/java/com/doonutmate/doonut/member/model/OauthTypeStrategy.java
> +    APPLE("appleMemberDelete");
제가 생각했을때 oauthType이 현재 시스템에서 전반적으로 사용되는데, 만약에 지금처럼 oauthType에 strategyName을 추가를 해버리면 기존 로직에서 필요없는 strategyName을 가지게 되는 문제가있고 추후에 기존 코드가 바뀔때 문제가 될수도있어 책임을 분리하고자 했습니다!

2024-03-16 00:02 UTC, jickDo commented on doonut-core/src/main/java/com/doonutmate/doonut/member/model/OauthTypeStrategy.java
> +    APPLE("appleMemberDelete");
하나로 합친다는 의미를 저는 두개의 enum이 사실상 중복이여서 하나로 사용하는 방향이 어떤지로 이해를 하였는데 맞을까요??
바로 위에서 설명한 이유때문에 enum을 분리하였는데 혹시 하나로 합치는게 더 좋은 방향일까요??
일단은 enum명에 strategy를 제외하는 것에는 공감하여 OauthTypeStrategy을 MemberDeleteOauthType로 이름으로 변경하였습니다.

2024-03-16 00:08 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/member/model/OauthTypeStrategy.java
> +    APPLE("appleMemberDelete");
이제 OauthTypeStrategy에 strategyName 필드 없애도 되지 않나용?

2024-03-16 00:09 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/member/model/OauthTypeStrategy.java
> +    APPLE("appleMemberDelete");
> 하나로 합친다는 의미를 저는 두개의 enum이 사실상 중복이여서 하나로 사용하는 방향이 어떤지로 이해를 하였는데 맞을까요??

맞습니다!

2024-03-16 00:12 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/controller/MemberController.kt
> +        @RequestParam memberDeleteOauthType: MemberDeleteOauthType,
@-RequestParam 명은 간결한게 좋을 것 같아요!
- MemberDeleteOauthType > OauthType

2024-03-16 02:38 UTC, jickDo commented on doonut-core/src/main/java/com/doonutmate/doonut/member/model/OauthTypeStrategy.java
> +    APPLE("appleMemberDelete");
이해했습니다. 애초에 읽을때 값을 반환하게 해뒀는데 state를 enum에 저장하고 있는게 이상했네요... 코드를 잘못 이해하고 사용한거같네요 🥲

enum이 값을 안가지게 되어서 기존 새로 생성한 enum도 삭제하고 기존 oauthType으로 사용하는 것으로 하겠습니다!

2024-03-16 03:33 UTC, merged