Feature/entity/calender
doonutmate/doonut-server pull request #48
Opened 2024-05-02 10:33 UTC by jickDo

** 변경점

------------------

v.2 버전업을 위해 캘린더 기능 추가로 새로운 엔티티를 식별할 필요성이 생김

그에따른 도메인영역 CALENDER entity, repository, flyway 식별 후 생성

2024-05-03 13:59 UTC, yeongunheo requested changes
고생하셨습니다!  
calender 오타만 calendar로 수정하는 것 외에 몇가지 코멘트 남겨두었습니다 🙇

2024-05-03 13:59 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calender/entity/CalenderEntity.java
> +import lombok.*;
의존성 파악을 위해서 import * 보다는 풀어쓰는게 좋을 것 같아요.  
인텔리제이에 미리 설정해두는게 좋습니다!  
- [[IntelliJ] Import 설정](https://invicr.github.io/2020/03/03/IntelliJ-Import-%EC%84%A4%EC%A0%95/)

2024-05-03 13:59 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calender/entity/CalenderEntity.java
> +public class CalenderEntity extends BaseTimeEntity {
오타인것 같네요!  

```suggestion
@Table(name = "calendar")
public class CalendarEntity extends BaseTimeEntity {
```

2024-05-03 13:59 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calender/entity/CalenderEntity.java
> +    String calenderName;
```suggestion
    String calendarName;
```

2024-05-03 13:59 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calender/entity/CalenderEntity.java
> +    Instant lastUploadDate;
createdAt, updatedAt과 맞춰서 firstUploadedAt, lastUploadedAt는 어떠신가요?

2024-05-03 13:59 UTC, yeongunheo commented on doonut-core/src/main/resources/db/migration/V20240501234456__calender_ddl.sql
> +    last_upload_date  TIMESTAMP                               NULL COMMENT '마지막 업로드 날짜',
포맷터 한번 돌리면 좋을 것 같아요!  

```suggestion
    first_upload_date TIMESTAMP                           NULL COMMENT '최초 업로드 날짜',
    last_upload_date  TIMESTAMP                           NULL COMMENT '마지막 업로드 날짜',
```

2024-05-03 13:59 UTC, yeongunheo commented on doonut-core/src/main/resources/db/migration/V20240501234456__calender_ddl.sql
> +    total_count       INT                                 NOT NULL COMMENT '총 기록 횟수',
여기도 DEFAULT 값 추가해야할 것 같아요.

```suggestion
    total_count       INT       DEFAULT 0                 NOT NULL COMMENT '총 기록 횟수',
```

2024-05-04 09:01 UTC, jickDo commented on doonut-core/src/main/java/com/doonutmate/doonut/calender/entity/CalenderEntity.java
> +import lombok.*;
이런설정법이 있었군요...! 의존성까지는 생각안해봤었는데 와일드카드로 설정되면 확실히 알기어려워보이네요 수정해두겠습니다!

2024-05-04 09:39 UTC, jickDo commented
** 추가 변경사항

---

1. 기존 `calender` 명칭을 `calendar`로 수정
2. 와일드카드 의존성을 풀어서 주입
3. 시간 변수명 일관성 맞추기 (firstUploadedAt, lastUploadedAt)
4. 포멧팅


---

이번 플라이웨이 수정은 히스토리로 남길필요가 없을것같아, 기존 테이블과 플라이웨이 calender 기록을 지우고 다시등록했습니다.

2024-05-04 11:17 UTC, yeongunheo approved these changes

2024-05-04 11:18 UTC, merged