Feature/jickchan/community
doonutmate/doonut-server pull request #50
Opened 2024-05-12 08:55 UTC by jickDo

** 변경점

1. 캘린더 조회 (최신순)

2024-05-13 14:34 UTC, yeongunheo requested changes
> 최신순 조회에 시간만 사용할경우 유니크한 값이 아니여서 데이터 유실이 일어날 가능성이 있다고하여, id와 updatedAt을 동시에 조회에 사용하게 구현하였습니다.  

슬랙에 적어주신 메시지 확인했는데요,  
updatedAt만 사용하여 페이징 처리를 하면 도중에 누군가 사진을 업로드했을 시 중간 데이터가 유실될 수 있다는 점을 말씀하신 것 같네요!  

여기서 한가지 의문인게 캘린더 조회시 데이터 유실이 발생하면 심각한 문제일까 인 것 같아요!  
제 생각엔 1~2개 정도 데이터 유실이 발생해도 괜찮지 않을까 합니다.  

페이스북이나 인스타그램에서도 무한스크롤 방식을 많이 사용하는데 포스트가 몇개 유실되더라도 다음 데이터가 나오면 괜찮으니까요.  

이 부분에 대한 직찬님 생각도 궁금하네요!

2024-05-13 14:34 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +    fun login(
동작에 맞게 메서드명 바꿔야할 것 같아요.  
```suggestion
    fun get(
```

2024-05-13 14:34 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +        return calendarService.get(id, time, PageRequest.of(0, 10))
pageSize를 클라이언트로부터 입력받게 한다면 요구사항의 변경에 좀 더 자유로워질 것 같아요.

2024-05-13 14:34 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +        @RequestParam(required = false) time: Instant?,
로그인한 사용자만 캘린더를 조회할 수 있기에 아래 코드도 추가되어야할 것 같아요.  
```kotlin
        @Authorization
        @Parameter(hidden = true)
        memberId: Long,
```

2024-05-13 14:34 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarService.kt
> +class CalendarService(
```suggestion
class CalendarAppService(
```

2024-05-13 14:34 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarService.kt
> +        val lastTimeOfList: Instant? = if (calendarList.isEmpty()) null else calendarList[calendarList.size - 1].updatedAt
변수명 간결하게 표현해도 좋을 것 같아요!  
- calendarList => calendars
- lastIdOfList => lastId
- lastTimeOfList => lastUpdatedAt

2024-05-13 14:34 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/dto/CalendarResponse.kt
> +    val lastUploadedAt: Instant,
현재 아래와 같이 UTC로 내려가고 있는데요,
아마 KST로 응답값을 내려드리는게 프론트 입장에선 더 편할 수도 있어요.

```
       "firstUploadedAt": "2024-05-12T16:40:35Z",
      "lastUploadedAt": "2024-05-12T16:40:35Z"
```

![스크린샷 2024-05-13 오후 11 04 59](https://github.com/doonutmate/doonut-server/assets/52141636/2c971600-3f51-40e2-b05d-c492ba2938e7)

UI에 맞게 `2024.04.01` String으로 내리는것에 대해선 어떻게 생각하시나요?

2024-05-13 14:34 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/dto/CalendarResponse.kt
> +    val imageUrl: List<ProfileImage>
서버 단에선 ProfileImage 이미지가 List이지만 프론트엔드에선 대표이미지 1개만 필요하기 때문에 혼란스러울 수 있어요.  
imageType이 REPRESENTATIVE인 이미지 1개만 내리는게 좋을 것 같습니다!

```suggestion
    val profileImageUrl: String
```

2024-05-13 14:34 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarService.kt
> +        val lastTimeOfList: Instant? = if (calendarList.isEmpty()) null else calendarList[calendarList.size - 1].updatedAt
[lastOrNull()](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/last-or-null.html)을 사용하면 좀 더 kotlin다운 코드가 될 것 같아요.

```suggestion
        val lastIdOfList: Long? = calendarList.lastOrNull()?.id
        val lastTimeOfList: Instant? = calendarList.lastOrNull()?.updatedAt
```

2024-05-13 14:34 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/repository/CalendarRepository.java
> +    List<CalendarEntity> findLatestCalendar(Instant cursor, Long cursorId, Pageable page);
JPARepository는 반환타입으로 List, Slice, Page를 모두 지원해요.
List가 아닌 Slice 타입을 반환하면 hasNext 값을 구하기 위해 Service 단에서 한번 더 조회 요청을 날릴 필요가 사라집니다!

```suggestion
    Slice<CalendarEntity> findLatestCalendar(Instant cursor, Long cursorId, Pageable page);
```

- 참고 : [[JPA] Slice & Page](https://colour-my-memories-blue.tistory.com/10)

2024-05-13 14:34 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/repository/CalendarRepository.java
> +    List<CalendarEntity> findLatestCalendar(Instant cursor, Long cursorId, Pageable page);
기존 스프링 진영에서는 페이징 처리시 Slice를 많이 사용했었는데요,  
SpringBoot 3.1 버전부터는 스크롤 API를 공식적으로 지원하기 시작했습니다!   

SpringBoot 3.1 버전부터 지원하는 [KeySet filtering](https://docs.spring.io/spring-data/jpa/reference/data-commons/repositories/scrolling.html#repositories.scrolling.keyset) 방식은 Slice가 아닌 Window 타입을 반환하는데요,  

Slice와 Window 타입 중 어떤 타입을 쓰는게 좋을지 한번 고민해봐도 좋을 것 같아요 😀
참고로, Window 타입에도 hasNext 정보를 갖고 있습니다!

2024-05-13 14:34 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarService.kt
> +        return if (id != null && time != null) {
id 또는 time만 존재한다면 어떤 일이 벌어지나요?

2024-05-13 14:39 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +@RequestMapping("/calendar")
REST API 설계 원칙에 따르면 url은 단수보다는 복수형을 추천하고 있어요.  
이미 설계한 API는 그대로 가더라도 이제부터 복수형으로 컨벤션을 가져가는건 어떨까요?

```suggestion
@RequestMapping("/calendars")
```

2024-05-15 08:16 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/dto/CalendarResponse.kt
> +    val lastUploadedAt: Instant,
시간형태를 고려하지 않았는데 생각해보니 필요에 맞게 내려주어야 겠네요 😀
kst로 변환후 형태 포맷팅해서 내려주도록 변경하겠습니다

2024-05-15 09:25 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +        return calendarService.get(id, time, PageRequest.of(0, 10))
이 부분은 고민을 했었습니다 이유는

```
페이저블 사이즈를 요청 받는다 -> 변화에 유용하게 대응 가능하다. 하지만 변화가 존재하지 않을경우 의미없는 파라미터를 계속해서 받아야한다.

페이저블 사이즈를 고정 시킨다 -> 변화가 발생하면 리팩토링해야 한다.
```
이러한 문제로 고민을 했었는데, 제가 내린 결론은 추가적인 요구사항이 식별되지 않았고 무한스크롤 방식에서 불러오는 데이터의 숫자가 중간에 달라지는 경우가 없다고 판단하였습니다. 물론 클라이언트의 요구의 변경으로 10개의 데이터 조회가 5개로 변하는 것은 가능하지만 api사용중 조회 데이터 개수가 10개에서 5개로 변경되는 경우가 없을것이라 판단하였습니다!

이부분은 어디가 맞는 방향인지 감이 안잡히는데 혹시 의견을 들을수 있을까요? 🥺

2024-05-15 09:34 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarService.kt
> +        return if (id != null && time != null) {
둘다 null로 들어온것과 같은 로직을 탑니다.

id와 updatedAt둘다 초기생성시 무조건 생성되는 값이라 `id가 있는데 time이 없거나` 혹은 `time이 있는데 id가 없거나` 두 경우 모두 불가능하다고 생각하고 있습니다.
현재 `id만 null이거나 time만 null 인경우` 발생하는 플로우는 없다고 생각하여 유효성검사는 하지 않았습니다.
물론 클라이언트 측에서 무조건 두 속성다 넣고 검색하거나, 두 속성 모두 null로 보내거나 해야하는 합의가 있어야 하긴합니다.

혹시 이부분도 밸리데이션을 해야하는걸까요...?🤔

2024-05-15 10:33 UTC, jickDo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/repository/CalendarRepository.java
> +    List<CalendarEntity> findLatestCalendar(Instant cursor, Long cursorId, Pageable page);
기존 리스트를 페이지네이션에 맞게 Slice나 Window로 반환하니 코드가 엄청 깔끔해지네요 😀
그런데 Window 타입은 정보가 많이 없어서 아직 어떤것이 더 좋을지는 조금더 고민해보고, 일단 slice타입 방식으로 push 해두겠습니다

2024-05-15 11:54 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarService.kt
> +        return if (id != null && time != null) {
`id만 null이거나 time만 null 인경우` 따로 밸리데이션 없이 null로 들어온 것과 같은 로직을 태우면 될 것 같아요!  
혹시 데이터가 유실되더라도 updatedAt 하나만 사용하는 것에 대해선 어떻게 생각하시나요?  
제 생각엔 1~2개 정도 데이터 유실이 발생해도 괜찮을 것 같아서요!

2024-05-15 11:58 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +        return calendarService.get(id, time, PageRequest.of(0, 10))
pageSize가 고정시켰을 때 변경비용 vs pageSize를 요청받았을 때 의미없는 파라미터를 계속 주고받는 비용 중 어떤게 큰지 생각해보면 좋을 것 같아요!  

pageSize를 계속해서 HTTP 파라미터로 주고받는건 서버 개발자의 리팩토링하는 리소스에 비해 큰 비용이 아니기에 보통은 변경에 최대한 열어두는 편입니다!

2024-05-15 13:19 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarService.kt
> +        return if (id != null && time != null) {
좋은것 같습니다. 꼭 두가지 조건으로 쿼리를 날려야 한다는 입장은 아니라 시간으로만 조회하도록 리팩토링 하겠습니다

2024-05-15 15:30 UTC, jickDo commented
*** 추가 변경점 

1. hasNext 제거 -> Slice 속성에 last라는 값이 이미 존재하며 hasNext와 같은 역할을 하고있음
2. 쿼리 조건에 id 제거
3. 클라이언트가 검색 사이즈를 조절할수있게 변경

2024-05-15 23:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +        return calendarService.get(id, time, PageRequest.of(0, 10))
가장 좋은 방법은 `CalendarRequest` 내에 pageSize 필드와 getDefaultPageSize라는 메서드를 추가하는 것이에요.  
서비스 단에서는 프론트로부터 넘어온 pageSize가 null이면 getDefaultPageSize 메서드를 호출해 10을 반환하면 직찬님이 고민하신 `변화가 존재하지 않을경우 의미없는 파라미터를 계속해서 받아야한다.`라는 문제를 해결할 수 있을 것 같습니다!  

혹시 이 방법에 대해선 어떻게 생각하시나요?

2024-05-16 23:43 UTC, yeongunheo requested changes

2024-05-16 23:43 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +    @GetMapping("/{size}")
size는 PathVariable 보단 RequestParam으로 받는게 좋을 것 같아요!

2024-05-16 23:43 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +        return calendarAppService.get(time, PageRequest.of(0, size))
사용자로부터 size가 들어오지 않을 시 서버 단 내부에서 defaultSize를 정의해서 사용한다면 `변화가 존재하지 않을경우 의미없는 파라미터를 계속해서 받아야한다.`라는 문제를 해결할 수 있을 것 같습니다!

2024-05-17 01:49 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +        return calendarAppService.get(time, PageRequest.of(0, size))
디폴트를 지정하고 처리하면 되는 문제였네요 제가 고려했던 부분을 처리할수있을거같네요

2024-05-17 02:13 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +        return calendarAppService.get(time, PageRequest.of(0, size))
사이즈가 null일경우 디폴트를 10으로 바꿧습니다!

2024-05-17 02:22 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/dto/CalendarResult.kt
> +    val values: Slice<T>,
응답값이 Slice 타입이면 클라이언트 입장에서 불필요한 정보도 나오기때문에 List가 좋을 것 같습니다!

```
{
  "values": {
    "content": [
      {
        "id": 10,
        "totalCount": 11,
        "memberName": "임직찬",
        "calendarName": "태스트캘린더 10",
        "updatedAt": "2024-05-12T15:22:26Z",
        "firstUploadedAt": "2024.05.13",
        "lastUploadedAt": "2024.05.13",
        "profileImage": "http://t1.kakaocdn.net/account_images/default_profile.jpeg.twg.thumb.R640x640"
      },
      {
        "id": 9,
        "totalCount": 10,
        "memberName": "임직찬",
        "calendarName": "태스트캘린더 9",
        "updatedAt": "2024-05-12T15:22:25Z",
        "firstUploadedAt": "2024.05.13",
        "lastUploadedAt": "2024.05.13",
        "profileImage": "http://t1.kakaocdn.net/account_images/default_profile.jpeg.twg.thumb.R640x640"
      },
      {
        "id": 7,
        "totalCount": 8,
        "memberName": "임직찬",
        "calendarName": "태스트캘린더 7",
        "updatedAt": "2024-05-12T15:22:23Z",
        "firstUploadedAt": "2024.05.13",
        "lastUploadedAt": "2024.05.13",
        "profileImage": "http://t1.kakaocdn.net/account_images/default_profile.jpeg.twg.thumb.R640x640"
      },
      {
        "id": 8,
        "totalCount": 9,
        "memberName": "임직찬",
        "calendarName": "태스트캘린더 8",
        "updatedAt": "2024-05-12T15:22:23Z",
        "firstUploadedAt": "2024.05.13",
        "lastUploadedAt": "2024.05.13",
        "profileImage": "http://t1.kakaocdn.net/account_images/default_profile.jpeg.twg.thumb.R640x640"
      },
      {
        "id": 5,
        "totalCount": 6,
        "memberName": "임직찬",
        "calendarName": "태스트캘린더 5",
        "updatedAt": "2024-05-12T15:22:21Z",
        "firstUploadedAt": "2024.05.13",
        "lastUploadedAt": "2024.05.13",
        "profileImage": "http://t1.kakaocdn.net/account_images/default_profile.jpeg.twg.thumb.R640x640"
      }
    ],
    "pageable": {
      "pageNumber": 0,
      "pageSize": 5,
      "sort": {
        "empty": true,
        "unsorted": true,
        "sorted": false
      },
      "offset": 0,
      "paged": true,
      "unpaged": false
    },
    "number": 0,
    "sort": {
      "empty": true,
      "unsorted": true,
      "sorted": false
    },
    "first": true,
    "last": false,
    "size": 5,
    "numberOfElements": 5,
    "empty": false
  }
}
```

2024-05-17 02:24 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +    private fun branchPageSize(size: Int?): Pageable {
메서드는 동사로 시작하는게 좋을 것 같아요.  

```suggestion
    private fun getBranchPageSize(size: Int?): Pageable {
```

2024-05-17 02:27 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +            calendarFacadeService.convertToList(calendarBusinessService.findInitialLatestCalendar(page))
분기문이 AppService가 아니라 BusinessService에 있다면 BusinessService의 메서드를 하나로 할 수 있을것 같아요.  
그럼 메서드명이 findCalendars로 바뀌면서 좀 더 응집도를 높일 수 있을 것 같습니다!

2024-05-17 02:29 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/service/CalendarBusinessService.java
> +        Slice<CalendarEntity> calendarEntityList = repository.findLatestCalendar(timeCursor, pageable);
timeCursor가 Null이면 안된다는 점은 이 메서드만 보고 판단할 순 없기에 위의 `findInitialLatestCalendar`와 합치는게 좋을 것 같습니다! AppService와 BusinessService를 모두 살펴봐야 이 쓰임을 제대로 알 수 있는 것 같아요.

2024-05-17 09:32 UTC, jickDo commented
**** 변경점

1. 기존에 분산되어있던 캘린더 조회 기능을 하나의 메서드로 함축
2. slice형태를 리스트로 클라이언트에게 반환
3. pathvariable -> requestparam 형태로 api파라미터 요청 변경

2024-05-18 01:04 UTC, yeongunheo approved these changes
고생하셨습니다!

2024-05-18 01:04 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +            "4. size가 null이면 10, null이 아니면 size크기만큼 조회됨",
Java 17의 Text Blocks처럼 Kotlin에도 [String Literal Multiline strings](https://kotlinlang.org/docs/strings.html#multiline-strings) 기능이 있어 여러 줄의 문자열을 손쉽게 표현할 수 있습니다!  

마크다운에서와 같이 줄 끝에 띄어쓰기 2번을 같이 입력하면 줄바꿈이 되더라구요.

```suggestion
                description = """ 
            1. 첫요청시 time은 null  
            2. 이후 요청시 마지막 속성의 updatedAt을 time 파라미터로 사용  
            3. 다음 조회가 불가능한 경우 hasNext가 false  
            4. size가 null이면 10, null이 아니면 size크기만큼 조회됨  
            """
```

스웨거 상에선 아래와 같이 표현됩니다!  

![스크린샷 2024-05-18 오전 9 55 30](https://github.com/doonutmate/doonut-server/assets/52141636/102fe179-19a5-4d2f-a39b-bec2ceaa1fbd)

2024-05-18 01:04 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/TimeZoneConverter.kt
이 파일 내 메서드는 doonut-support 모듈 내 CommonDateUtils에 있어도 좋을 것 같아요.

2024-05-18 01:04 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/service/CalendarBusinessService.java
> +    public Slice<Calendar> convertListEntityToDto(Slice<CalendarEntity> calendarEntityList) {
클래스 내부에서만 사용하므로 접근제어자 private으로 바꾸는게 좋을 것 같습니다.

2024-05-18 01:04 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/service/CalendarBusinessService.java
> +    public Slice<Calendar> convertListEntityToDto(Slice<CalendarEntity> calendarEntityList) {
findCalendars 메서드 바로 아래 두는게 가독성이 좀 더 좋을 것 같아요.

2024-05-18 06:14 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +            "4. size가 null이면 10, null이 아니면 size크기만큼 조회됨",
이런게 있었군요...! 방금 스웨거로 확인하니까 이쪽이 가독성이 훨씬 괜찮은거같네요.

2024-05-18 06:53 UTC, jickDo commented
코드 리뷰 고생하셨습니다 🥹
 요청사항 변경하였고 머지하겠습니다!

2024-05-18 06:55 UTC, merged