Feature/jickchan/update mypage
doonutmate/doonut-server pull request #54
Opened 2024-05-24 13:25 UTC by jickDo

** 변경점

1. 프로필내 이름과 이미지 업데이트
2. 테스트 추가

2024-05-24 23:51 UTC, yeongunheo requested changes

2024-05-24 23:51 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/controller/MemberController.kt
> +        @RequestParam("name") name: String,
PUT이나 POST 요청에는 `@RequestParam` 대신 `@RequestBody`를 쓰는게 좋을 것 같아요.
- 참고 : https://stackoverflow.com/questions/47457382/can-i-use-requestparam-annotation-for-a-post-request

2024-05-24 23:51 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/service/MemberProfileFacadeService.kt
> +        val imageDto: ImageUploadResponse = imageAppService.saveFile(multipartFile, memberId)
이 메서드를 재사용하면 ImageAppService.saveFileToDb에서 챌린지에 데이터가 저장되는 의도치 않은 결과가 발생합니다 😢  
ImageAppService의 로직은 최대한 재사용하면서 챌린지에도 저장하지 않게 만들 수 있을까요?

2024-05-24 23:51 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/member/service/MemberBusinessService.java
> +        MemberEntity newEntity = getEntity(memberId);
기존 Entity를 갖고왔으니 newEntity라는 말은 조금 안어울리는 것 같아요!

2024-05-24 23:51 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/member/service/MemberBusinessService.java
>          var newEntity = mapper.toEntity(member);
위와 동일합니다!

2024-05-26 09:13 UTC, yeongunheo approved these changes
고생하셨습니다!

2024-05-26 09:13 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/member/entity/MemberEntity.java
> +    public void updateNameOrProfileImage(String name, List<ProfileImageEntity> newProfileImages) {
`updateNameAndProfileImage`가 좀 더 적절할 것 같네요!

```suggestion
    public void updateNameAndProfileImage(String name, List<ProfileImageEntity> newProfileImages) {
```

2024-05-26 09:13 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/image/service/ImageFacadeService.kt
> +    fun exposeSaveImage(multipartFile: MultipartFile, key: String, memberId: Long): String {
단순히 궁금해서 질문드리는건데 `expose-`는 어떤 의도에서 붙이신건가요?!

2024-05-26 09:13 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/image/service/ImageFacadeService.kt
>      private fun saveImage(multipartFile: MultipartFile, key: String, memberId: Long): String {
exposeSaveImage 메서드가 단순 bypass 메서드라면 이 메서드의 접근자를 public으로 바꿔도 괜찮을 것 같아요.

2024-05-26 09:13 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/image/service/ImageFacadeService.kt
기존 save 메서드명을 `saveChallenge`로 바꾸는건 어떨까요?

2024-05-26 09:13 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/image/service/ImageAppService.kt
saveProfileImage라는 메서드명이 생겼으니 기존 메서드명도 좀 더 의도를 명확하게 드러내는게 좋을 것 같아요!  
- saveFile -> saveChallenge
- saveFileToDb -> saveChallengeToDb

2024-05-26 09:13 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/controller/dto/NameRequest.kt
> +    val nickname: String
프론트에서 1차 검증해서 넘어오니 간단하게 Req 객체 내에서 Validation 걸어줘도 좋을 것 같아요.  

```suggestion
    @Schema(title = "닉네임")
    @jakarta.validation.constraints.NotBlank
    @jakarta.validation.constraints.Size(min = 1, max = 8)
    val nickname: String
```

2024-05-26 09:13 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/controller/MemberController.kt
> +        @RequestPart("nameRequest") nameRequest: NameRequest,
```suggestion
        @jakarta.validation.Valid @RequestPart("nameRequest") req: NameRequest,
```

2024-05-26 09:13 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/controller/MemberController.kt
> +    fun updateProfile(
포스트맨에선 정상동작하는 것 확인했는데, 스웨거 상에선 에러가 발생하더라구요.  
혹시 원인이 무엇인지 아시나요?

![스크린샷 2024-05-26 오후 5 48 13](https://github.com/doonutmate/doonut-server/assets/52141636/ad6354f4-3f44-4f71-8e4c-cdd83a62cb2c)

2024-05-26 09:13 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/controller/MemberController.kt
사용자가 저장할 때 클릭을 2번하면 프로필이미지가 2개 생기는 것 같네요(동시성 이슈).    
일단은 프론트엔드에서 방어해달라고 요청드리면 그냥 넘어가도 될 것 같아요.

![스크린샷 2024-05-26 오후 6 07 38](https://github.com/doonutmate/doonut-server/assets/52141636/70f1129b-5901-41c2-b2ae-4a43509990b7)

2024-05-26 09:13 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/image/service/ImageFacadeService.kt
> +    fun exposeSaveImage(multipartFile: MultipartFile, key: String, memberId: Long): String {
기존 private 메서드명과 겹쳐서 `expose-` prefix가 붙었나보네요.

2024-05-26 10:17 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/image/service/ImageFacadeService.kt
> +    fun exposeSaveImage(multipartFile: MultipartFile, key: String, memberId: Long): String {
맞습니다! 기존 이미지 저장 메서드가 private이다보니 기존코드를 수정하지 않고 확장을 하려다 보니 private을 public으로 만들어줄메서드가 필요했습니다.

2024-05-26 10:27 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/image/service/ImageFacadeService.kt
>      private fun saveImage(multipartFile: MultipartFile, key: String, memberId: Long): String {
`exposeSaveImage`를 사용해서 public 접근제어자를 따로 생성하는 방법에서 기존 메서드를 public으로 변경시키는 방식으로 바꿔두었습니다!

2024-05-26 10:38 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/image/service/ImageFacadeService.kt
`save` 메서드 안에 `saveChallenge`와 `saveImage`가 이미 존재하고 있습니다. `save`는 이미지와 캘린더 저장을 동시에 처리하는 메서드 같고, `save`메서드를 `ImageAppService`에서 `saveFileToDb`라는 메서드로 받고있습니다.

이 메서드가 이름을 봤을 때 이미지와 챌린지의 정보를 저장한다는 의미가 떨어지는거 같아 `saveImageAndChallenge`와 같은 명확한 이름으로 만드는것은 어떠신가요!

2024-05-26 10:39 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/image/service/ImageAppService.kt
차례대로 읽다보니 아래에서 명확한 네이밍에 대해서 말씀하셨군요...! 챌린지, 파일, 이미지등 의미가 헷갈리는 표현들이 많다고 느껴서 정리를 해보겠습니다

2024-05-26 11:57 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/controller/MemberController.kt
> +    fun updateProfile(
찾아보니, 특별히 표현할 방법이 없는경우 `octet-stream`으로 콘텐츠 타입이 정해진다고 합니다. 그런데 `octet-stream `타입을 스웨거에서 타입을 허용하지 않고 있어서 문제가 되는거같습니다.

octet-stream 타입을 받을수 있는 설정은 스웨거 config파일에서 설정을 추가적으로 해뒀습니다.

단일 이미지 업로드는 문제가 없는데 json타입이랑 사진을 같이 보낼때 문제가 되는거같은데, 이부분에 대해서는 저도 이유를 모르곘습니다.

2024-05-26 11:58 UTC, jickDo commented
변경사항 적용해두었습니다!

2024-05-26 12:08 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/member/controller/MemberController.kt
> +    fun updateProfile(
지금은 정상적으로 잘 동작하네요!

2024-05-26 12:18 UTC, merged