Feature/jickchan/update calendar
doonutmate/doonut-server pull request #57
Opened 2024-05-28 11:02 UTC by jickDo

** 변경점

1. feat: 토큰을 이용한 캘린더 제목 조회
2. feat: 토큰을 이용한 캘린더 제목 수정

2024-05-29 13:10 UTC, yeongunheo requested changes

2024-05-29 13:10 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
>  @RestController
import문과 본문 사이에 줄바꿈이 필요할 것 같아요.
```suggestion

@RestController
```

2024-05-29 13:10 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +    @Operation(summary = "캘린더 조회", description = "멤버가 자신의 캘린더 제목을 조회한다.(토큰사용)")
summary하고 description 정보가 같다면 summary만 사용해도 될 것 같아요. 
```suggestion
    @Operation(summary = "캘린더 제목 조회")
```

2024-05-29 13:10 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +    @Operation(summary = "캘린더 설정", description = "멤버가 캘린더 제목을 수정한다.(토큰사용)")
```suggestion
    @Operation(summary = "캘린더 제목 설정")
```

2024-05-29 13:10 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +    @Operation(summary = "캘린더 설정", description = "멤버가 캘린더 제목을 수정한다.(토큰사용)")
토큰 사용이란 말은 따로 설명에 붙이신 이유가 있을까요?

2024-05-29 13:10 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +        validate(memberId)
validate 내에서 캘린더명을 설정하지 않은 사용자는 에러가 발생할거라 의도치 않은 결과를 낳을 것 같습니다.

2024-05-29 13:10 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +        return calendarBusinessService.getByMemberId(memberId)
memberId에 해당하는 캘린더가 없다면 `NullPointerException`이 터지지 않을까요?

2024-05-29 13:10 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +            return updateCount > NOT_UPDATED
이 검증은 불필요한 것 같습니다.  
캘린더명을 설정하는건 upsert 문처럼 동작한다고 생각해요! 기존 캘린더명하고 동일하더라도 그대로 반영해서 정상응답 하는게 좋을 것 같아요.

2024-05-29 13:10 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/repository/CalendarRepository.java
> +    @Transactional
`@Transactional`은 리포지토리가 아닌 서비스 단에만 붙여도 충분하다고 생각합니다.  
직찬님은 어떻게 생각하시나요?

2024-05-29 13:10 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/repository/CalendarRepository.java
> +    Slice<CalendarEntity> findInitialLatestCalendar(Pageable page);
사용하지 않는 메서드라 삭제하는게 좋겠네요.

2024-05-29 13:10 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/service/CalendarBusinessService.java
> +    }
혹시 명령 쿼리 분리원칙에 대해 들어보셨나요?  

『오브젝트』, 조영호 p202
> 명령-쿼리 분리 원칙의 요지는 오퍼레이션은 부수 효과를 발생시키는 명령이거나 부수효과를 발생시키지 않는 쿼리 중 하나여야 한다는 것이다. 어떤 오퍼레이션도 명령인 동시에 쿼리여서는 안 된다. 따라서 명령 쿼리를 분리하기 위해서는 다음의 두 가지 규칙을 준수해야 한다.

- 객체의 상태를 변경하는 명령은 반환값을 가질 수 없다.
- 객체의 정보를 반환하는 쿼리는 상태를 변경할 수 없다.

이 메서드는 상태를 변경하는 명령쿼리임에도 불구하고 반환값을 가지기 때문에 `명령-쿼리 분리 원칙`에 위배된다고 생각하는데, 직찬님의 이에 대해 어떻게 생각하시나요?

2024-05-29 22:51 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +    @Operation(summary = "캘린더 설정", description = "멤버가 캘린더 제목을 수정한다.(토큰사용)")
최근에 다른곳에서 협업 진행 하면서 토큰을 사용하였던 경험이 있었는데, 파라미터가 히든인 상황에서 스웨거만 보고 토큰사용 유무를 알아내기 어렵다는 대화를 한적이 있었습니다.

지금까지 토큰 사용에 대한 설명이 없어서 이것을 description에 붙이면 더 혼란스러울 수도 있겠다는 생각이 드네요
지우는 방향으로 갈까요??

2024-05-29 22:55 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +        return calendarBusinessService.getByMemberId(memberId)
validate내부에 `NPE`검증 로직이 있어서 따로 검증을 하지 않았습니다!

` val calendar = calendarBusinessService.getByMemberId(memberId)
            ?: throw CalendarException("캘린더를 찾을 수 없습니다. memberId: $memberId")`

2024-05-29 23:07 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +        validate(memberId)
첫 캘린더 제목에 대해서 생성로직이 있다고 생각하고 있었습니다. 그렇기 때문에 캘린더 제목이 없는 경우 캘린더 제목 수정을 들어갔을 때 에러 창으로 `캘린더 제목이 없습니다`와 같은 문구가 생성되는 것을 기대했습니다.

그런데, 캘린더 제목 초기생성이 없고 제목수정 뷰에서 첫생성을 진행한다면 확실히 문제가 될것 같습니다.
이부분은 기획자님께 여쭤보고 다시 이야기 해보시는것 어떠신가요!

2024-05-29 23:53 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +            return updateCount > NOT_UPDATED
첫 의도는 업데이트 구문에 문제가 생겼을때 업데이트가 반영이 되지 않았다는 것을 설명하기 위한 의도였습니다. 동일한 업데이트에 관해서는 확신이 없어서, 테스트를 해봤었는데 업데이트가 된 판정이였습니다!.

처음 생각했던 부분은 `calendarBusinessService.updateCalendarName`이 부분이 트랜잭션 처리가 되어있어서 걱정안해도 될것 같습니다.

그런데, 트랜잭션이 업데이트가 실패하면 

```
1. 롤백이 되고 진행된다.
2. 예외를 반환한다.
```

위 두가지 경우중 어떤것으로 진행되는지 모르겠어서, 찾아 보았는데 

```
RuntimeException -> 트랜잭션 롤백
CheckedException -> 트랜잭션 커밋
```

이렇게 진행 된다고 합니다.
혹시, checkedException이 발생하였을때 트랜잭션 커밋이 진행된다면 문제가 생길수 있다는 생각이 듭니다.

당장 생각나는 방법은

`updateCalendarName `메서드의 선언적 트랜잭션 부분을 `@Transactional(rollbackFor=Exception.class)`처럼 모든 예외에 대해서 롤백시키는 방법도 괜찮을것 같습니다.

조금 길게 말했는데 이부분에 대해서 잘못된 부분이나 생각이 있다면 말씀해주시면 정말 감사하겠습니다!!

2024-05-29 23:54 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +    @Operation(summary = "캘린더 설정", description = "멤버가 캘린더 제목을 수정한다.(토큰사용)")
넵 전 이미 프론트엔드와 합의되어 있다고 생각해서 제거해도 좋을 것 같아요!  
회원가입처럼 특정 url을 제외하고 모두 이미  토큰 기반으로 통신하고 있어서요.

2024-05-30 00:11 UTC, jickDo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/repository/CalendarRepository.java
> +    @Transactional
저도 트랜잭션은 서비스 영역에서만 다루는게 좋은것 같습니다. 변경사항 수정하겠습니다

2024-05-30 00:11 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +    // TODO 현재 전역예외처리에 @Valid 에러가 넘어가서 400으로 나온다. 이문제를 @Valid전용 전역설정을 만들어야 한다.
이 주석은 `MethodArgumentNotValidException` 따로 catch하는 걸 의미하는 건가요?

2024-05-30 00:13 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +        validate(memberId)
저도 기획 플로우를 같이 이야기해보고 정하는게 좋을 것 같아요.  
기존 사용자들은 캘린더 테이블에 데이터가 없을텐데 이 문제를 어떻게 풀 지도 고민해봐야겠네요!

2024-05-30 00:21 UTC, jickDo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/repository/CalendarRepository.java
> +    Slice<CalendarEntity> findInitialLatestCalendar(Pageable page);
develop브랜치와 머지하면서 해결했습니다!

2024-05-30 01:01 UTC, jickDo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/service/CalendarBusinessService.java
> +    }
엄청 좋은 의견인것 같습니다..!!

이렇게 진행한다면 컨트롤러 반환값까지 무언가를 리턴해줄 필요가 없다고 생각합니다!

그런데 이번주 회의록 확인했을 때 성공 코드에 대한 협의는 없었던것 같습니다! 
사실 성공한 경우를 의미있게 표현하는게 의미가 있나 싶긴하지만..? 당장 던질수 있는 방식은 `return ResponseEntity.ok().build()` 라고 생각이 듭니다. 
그렇게 되면 프론트에서는 200번 성공에 대한 코드만 확인할 수 있는데 이런 리턴 방식은 어떻게 생각 하시나요!?

2024-05-30 01:06 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +    // TODO 현재 전역예외처리에 @Valid 에러가 넘어가서 400으로 나온다. 이문제를 @Valid전용 전역설정을 만들어야 한다.
넵 맞습니다.
원래는 valid가 터졌을 경우 기존에 설정한 설명이 반환되는 것으로 알고있는데, 현재는 400번 전역설정 에러가 반환되는것 같습니다.
```
{
  "type": "about:blank",
  "title": "Bad Request",
  "status": 400,
  "detail": "Invalid request content.",
  "instance": "/calendars/profile"
}
```

이렇게 반환되는 경우는 프론트측에서 어떤 문제인지 알기어렵다고 생각이 듭니다..!

2024-05-30 01:33 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +        validate(memberId)
슬랙 `general` 통해서 기획자분이랑 이야기를 해봤는데 캘린더 생성을 할때 `사용자 닉네임 캘린더`이렇게 붙어서 캘린더가 존재하는데 캘린더명이 없는 경우는 없을것 같습니다!

2024-05-30 04:19 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +        validate(memberId)
그럼 운영 배포 전에 기존에 캘린더가 없는 사용자들은 전부 `박수치는 물개님 캘린더`와 같은 형식으로 DB INSERT를 하실 예정인가요?

![image](https://github.com/doonutmate/doonut-server/assets/52141636/0e92dc91-4a4e-413d-a5e3-72a18dc4af71)

2024-05-30 04:20 UTC, yeongunheo commented on doonut-core/src/main/java/com/doonutmate/doonut/calendar/service/CalendarBusinessService.java
> +    }
따로 반환값이 없다면 `ResponseEntity.ok().build()`로 프론트에 전달해줘도 괜찮을 것 같아요.

2024-05-30 04:21 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/CalendarController.kt
> +    // TODO 현재 전역예외처리에 @Valid 에러가 넘어가서 400으로 나온다. 이문제를 @Valid전용 전역설정을 만들어야 한다.
넵 나중에 따로 추가하는걸로 하죠!

2024-05-30 04:23 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +            return updateCount > NOT_UPDATED
제가 잘 이해를 못했는데, `calendarBusinessService.updateCalendarName(memberId, title)`에서 실패가 나는 상황이 있나요?

2024-05-30 07:43 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +        validate(memberId)
아... 생각해보니 그러네요 .. 기존 유저의 데이터는 생각해보지 못했습니다.
디폴트 이름을 유지하면서 기존유저의 캘린더를 생성할 방법을 고민을 해보고 있는데 지금 방식으로 가면 DB INSERT 말고는 별다른 방법이 없어보이네요

캘린더를 생성하는 뷰를 추가적으로 생성하는게 좋은지, DB INSERT방식으로 구현하는게 좋은지 잘모르겠습니다. 두 부분다 명확한 문제가 있다고 생각이 들어서 선뜻 결정하기 어려운것 같습니다.
가능하다면 영운님의 조언을 듣고 싶습니다.

2024-05-30 08:22 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +            return updateCount > NOT_UPDATED
실패가 발생하는 예외를 예상한것은 아니고, `Checked Exception`중 예상하지 못한 문제에 관한 처리를 하려는 생각이었습니다.
`Checked Exception`은 확실한 경우중에 적절한 대응이 가능할 경우에만 잡는것이 좋다고 알고 있는데, 무리한 예외처리를 한것같네요

2024-05-31 06:45 UTC, yeongunheo approved these changes
고생하셨습니다!

2024-05-31 06:45 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/dto/CalendarNameRequest.kt
> +    @field:Size(min = 1, max = 12, message = "캘린더 제목은 최소 1자에서 최대 8자입니다.")
field 없어도 동작하지 않나요?  
```suggestion
    @NotBlank(message = "캘린더 제목은 공백 일 수 없습니다")
    @Size(min = 1, max = 12, message = "캘린더 제목은 최소 1자에서 최대 8자입니다.")
```

2024-05-31 06:45 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/dto/CalendarNameRequest.kt
> +    @field:Size(min = 1, max = 12, message = "캘린더 제목은 최소 1자에서 최대 8자입니다.")
캘린더 제목은 1~8자인데, @Size(max=12)로 해놓으신 이유가 있을까요?

2024-05-31 06:45 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +        private const val NOT_UPDATED = 0
더이상 사용하지 않아서 지워도 될 것 같아요.

2024-05-31 06:45 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +        }
try-catch문 없애도 될 것 같아요.  

```suggestion
        calendarBusinessService.updateCalendarName(memberId, title)
```

2024-05-31 06:45 UTC, yeongunheo commented on doonut-support/src/main/java/com/doonutmate/exception/ErrorCode.java
> +    COMMUNITY_NOT_ACCESSIBLE, NOT_UPDATED
NOT_UPDATED 제거해도 될 것 같습니다!

2024-05-31 07:49 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/service/CalendarAppService.kt
> +        validate(memberId)
캘린더를 생성하는 뷰를 추가적으로 만들면 기획이랑 디자인 단에서 추가적인 리소스가 들어갈거라 운영 DB INSERT로 가도 될 것 같아요.  
DB INSERT문 미리 만들어두고, 운영 배포 전 사전체크리스트에 넣어두면 좋을 것 같습니다!

2024-05-31 08:53 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/dto/CalendarNameRequest.kt
> +    @field:Size(min = 1, max = 12, message = "캘린더 제목은 최소 1자에서 최대 8자입니다.")
Valid작동 테스트 해보다가 알게된 사실인데, 코틀린에서는 @Valid 관련 어노테이션에 대상을 붙여주어야 한다고 합니다. 대상이 없다면 @Target에 따라 정해진다고 합니다.

filed 때고 날려도 보았는데 @Valid가 작동하지 않네요

https://ttl-blog.tistory.com/833

https://kotlinlang.org/docs/annotations.html#annotation-use-site-targets

2024-05-31 08:56 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/dto/CalendarNameRequest.kt
> +    @field:Size(min = 1, max = 12, message = "캘린더 제목은 최소 1자에서 최대 8자입니다.")
> 캘린더 제목은 1~8자인데, @SiZe(max=12)로 해놓으신 이유가 있을까요?

이부분은 message부분이 잘못된것 같습니다. 수정해두겠습니다..!

기능 명세서 마이페이지 부분 발췌
`제목은 공백포함 최소 1자 최대 12자를 적을 수 있다.`

2024-06-01 04:06 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/calendar/controller/dto/CalendarNameRequest.kt
> +    @field:Size(min = 1, max = 12, message = "캘린더 제목은 최소 1자에서 최대 8자입니다.")
코틀린에서는 Spring Validation이 `@field:` 붙여야 동작하는지는 몰랐네요! 덕분에 하나 배워갑니다 🙇

2024-06-01 05:17 UTC, merged