Feature/limjickchan/doon 23
doonutmate/doonut-server pull request #6
Opened 2023-10-31 09:19 UTC by jickDo

*변경점

- oauth 패키지 생성
- kakaoOauthConfig 안에 스웨거 그룹화
- 컨트롤러에서 바디로 토큰을 받고 카카오 사용자 id 리턴 (여기 api는 추후 로그인으로 바꿀예정, 테스트용으로 이름과 다른목적으로 만들어둠)
- tokenRequest dto생성 
- 서비스 getKakaoUserId구현 (토큰을 입력받고 사용자 정보를 받아 json parser로 id만 리턴하는 방식으로 구현)

토큰이 없어서 postman으로 개인 애플리케이션 토큰 생성받고 테스트 했습니다.
*swagger test*

![image](https://github.com/doonutmate/doonut-server/assets/95222741/9f82ba19-d017-438c-a524-d17fccfd3150)

2023-10-31 09:52 UTC, oereo reviewed
고생하셨습니다!!
제 생각에 대한 리뷰 남겨놓았습니다!

2023-10-31 09:52 UTC, oereo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +        val kakaoUserInfoEndPoint = UriComponentsBuilder.fromHttpUrl("https://kapi.kakao.com/v2/user/me")
흠 개인적인 생각이지만! 저는 `https://kapi.kakao.com/v2/user/me`와 같은 값은 개인적으로 상수로 분리하는게 좋아 보입니다!
```kotlin
private static final String KAKAO_USER_INFO_END_POINT = "";
```

2023-10-31 09:52 UTC, oereo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +    fun getKakaoUserId(accessToken: String): Long {
`https://kapi.kakao.com/v2/user/me`를 통해 가져오는 정보가 현재로써는 userId만 있는 것 같아서 method를 구현하신 것 같지만! 나중에 여러 정보를 가져오게 된다고 하면 이 method의 형식은 결국 바뀌어야 되겠구나 라는 생각이 듭니다!

저의 개인적인 생각은 이 method의 역할을 보게 되면 kakao endpoint를 통해 요청을 하고 그에 대한 데이터(json)을 파싱해서 userId를 return 하는 느낌인데 이 역할을 method들을 분리해서 사용하는 것은 어떠한지 의견을 여쭈어봅니다!!

`kakao endpoint를 통해 데이터를 받아오는 method`와 `받아온 데이터에서 원하는 값을 반환하는 method` 이렇게 2개로 쪼개는 것은 어떠할까요??
`kakao endpoint를 통해 데이터를 받아오는 method`에서는 결국 front에서 넘어온 token이 잘못될 경우에 대한 exception handler 로직이 같이 들어가서 순수한 카카오 유저 정보를 가져오는 행위에 목적을 맞추는것도 좋을 것 같습니다!

2023-10-31 09:52 UTC, oereo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +        val restTemplate = RestTemplate()
이거 매번 인스턴스로 만들어야 하는지 궁금하네요!!

2023-10-31 09:52 UTC, oereo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/dto/TokenRequest.kt
> +    @Schema(title = "토큰", example = "")
title에 카카오에서 발급된 accessToken이라는 느낌의 설명을 붙이는 것이 좋아보일 것 같아요!!
swagger에서 보면 헷갈릴 여지가 있을 수 있을 것 같습니다!

2023-10-31 09:52 UTC, oereo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/dto/LoginUserInformationDto.kt
> +//    val member: Member,,
나중에 Member에 대한 정보도 DTO에 담길 예정이라면 TODO를 통해서 기록해주시는 것도 좋아보입니다!!

2023-10-31 10:43 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +    fun getKakaoUserId(accessToken: String): Long {
오... 생각해보니 method를 분리하면 더 유연하게 사용할 수 있겠네요!!
리턴값에 대해서 고민했었던 부분들이 해결 되었습니다.
이 부분은 생각을 못했었는데 피드백 감사드립니다.

2023-10-31 10:50 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/dto/TokenRequest.kt
> +    @Schema(title = "토큰", example = "")
헷갈릴 여지가 있어보이네요 이부분은 정정하겠습니다!

2023-10-31 15:28 UTC, yeongunheo requested changes

2023-10-31 15:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +        val kakaoUserInfoEndPoint = UriComponentsBuilder.fromHttpUrl("https://kapi.kakao.com/v2/user/me")
저도 상수로 표현하는게 좋을 것 같네요.  
아니면 application.yml 파일에 설정해서 @Value로 주입받는 방법도 좋을 것 같아요.

2023-10-31 15:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +        return jsonObj["id"] as Long
이 부분을 유틸 클래스로 분리하면 나중에 애플로그인 할 때 처럼 다른 곳에서도 사용할 수 있을 것 같아요!

2023-10-31 15:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +        )
만약 유효하지 않은 Access Token이 입력되면 어떤 에러가 발생하나요?  
저희 내부에서 정의한 커스텀 에러와 에러 메시지가 필요할 것 같아요!

2023-10-31 15:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +        val restTemplate = RestTemplate()
RestTomplate 방식 대신 HTTP Interface 방식을 사용해볼 수 있을까요?  
참고 문서와 예제 코드 남겨놓을게요!

- https://www.baeldung.com/spring-6-http-interface
- https://github.com/YAPP-Github/onboard-server/blob/cd2951562e26d0d016672dc27e6d6bf2c6658be2/adapter-out/social/src/main/kotlin/com/yapp/bol/social/kakao/KakaoOpenApiClient.kt

2023-10-31 15:28 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +        val restTemplate = RestTemplate()
아래처럼 HTTP Interface 방식을 사용하게 되면 jsonParser를 사용하지 않아도 될 것 같은데, 이 방법도 한번 알아봐주실 수 있을까요?

```kotlin
internal interface KakaoOpenApiClient {
    @GetExchange("/v2/user/me")
    fun getTokenInfo(
        @RequestHeader("Authorization") authorization: String,
    ): Mono<KakaoUserResponse>
}
```

```kotlin
data class KakaoUserResponse(val id: String)
```

2023-10-31 19:45 UTC, oereo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +        )
카카오 문서 기준으로는 아래와 같은 error response를 kakao에서 반환하는 것 같습니다!

status code : `401`

HTTP/1.1 401 Unauthorized  
WWW-Authenticate: Bearer error=invalid_token

```json
{
  "code":-401,
  "msg":"InvalidTokenException"
}
```

2023-10-31 23:54 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +        val restTemplate = RestTemplate()
넵 HTTP Interface방식으로 리팩토링 해보겠습니다!

2023-11-01 01:12 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +        val kakaoUserInfoEndPoint = UriComponentsBuilder.fromHttpUrl("https://kapi.kakao.com/v2/user/me")
### 상수선언
`companion object{ const val KAKAO_USER_INFO_END_POINT = ""}`


### @Value
`    @Value("\${END_POINT.KAKAO_USER_INFO}")`
`    private lateinit var kakaoUserInfoEndPoint: String`

세훈님과 영운님의 말씀을 듣고 고민을 하였는데, 추후에 endPoint들이 추가 되었을때 유지보수하기 후자쪽이 편하다고 판단이 들었습니다.
`END_POINT:`
` KAKAO_USER_INFO: ""`
yml에 이렇게 추가하여 다른 endPoint가 생겨났을 때 확장하는 방식으로 가겠습니다!!

2023-11-01 03:27 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/service/OauthService.kt
> +        val restTemplate = RestTemplate()
HTTP Interface 적용했고 id불러오는 함수와 info전부 불러오는 함수를 일단은 만들어 두었습니다. swagger로 확인하니 작동 되네요 :)
반환타입에 무엇이 위치 하는지 따라 파싱되는 것 같긴한데 이 부분은 밥먹고 확인해보도록 하겠습니다

2023-11-01 07:39 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/.DS_Store
`.DS_Store` 파일이 추가되었네요!  
이 파일 삭제해주시고 gitigonre에 추가하면 좋을 것 같아요.

2023-11-01 07:40 UTC, yeongunheo approved these changes
고생하셨습니다.

2023-11-01 07:59 UTC, yeongunheo commented on doonut-app-external-api/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-webflux")
webflux 의존성은 어떤 이유로 추가하신건가요?

2023-11-01 08:53 UTC, jickDo commented on doonut-app-external-api/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-webflux")
http interface 사용할때 webclient를 사용하는데 그게 webflux의존성을 가집니다.

2023-11-01 14:29 UTC, jickDo commented
리뷰 달아주셔서 감사합니다 🥹

2023-11-01 14:29 UTC, merged