Feature/jickchan/doon 28
doonutmate/doonut-server pull request #8
Opened 2023-11-03 04:43 UTC by jickDo

implementation("org.springframework.boot:spring-boot-starter-data-jpa")

2023-11-03 20:25 UTC, oereo reviewed
리뷰 간단히 남겼습니다! 제가 이후에 더 자세하게 코드 보고 리뷰 남기도록 하겠습니다!!

2023-11-03 20:25 UTC, oereo commented on doonut-app-external-api/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
`implementation("org.springframework.boot:spring-boot-starter-data-jpa")`에 대해서요. 지금 doonut-app-external-api의 build.gradle에 dependency 추가하신 것 같아서요! doonut-core에서 repository를 JPA Repository를 쓰시려면 추가되어야 할것 같은데 doonut-core module에 dependency로 추가하는 방향으로 가는건 어떠신가요??

```java
api("org.springframework.boot:spring-boot-starter-data-jpa")
```

2023-11-03 20:25 UTC, oereo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/controller/KakaoOauthController.kt
> +    @PostMapping("login/{oauthType}")
이 API가 위의 `getKakaoSelctedUserInfo`와의 차이점이 무엇일까요?? 지금 API 인자를 받는 부분을 보면 PathVariable의 oauthType만 있는 것 같은데 이 API url prefix를 보면 kakao라고 되어있어서요! oauthType을 따로 받는 이유와 API를 나눠서 개발한 부분이 궁금합니다!!

front쪽에서는 카카오 accessToken을 굳이 백엔드에 보내면서 카카오 프로필 정보를 받아올 이유는 사실 없어 보여서요!!
front쪽에서 바로 accessToken 담아서 카카오쪽에 요청 보내면 되니까요!

2023-11-03 20:25 UTC, oereo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/service/KakaoOauthLoginService.kt
> +    fun kakaoSignUpNewMember(tokenRequest: KakaoTokenRequest, oauthType: OauthType): Member? {
`oauthType` parameter가 사용되는건가요??!

2023-11-04 09:16 UTC, yeongunheo requested changes
코멘트 몇 줄 남겼습니다!  
이해 안되는 부분 있으면 편하게 말씀해주세요 ( _ _ )

2023-11-04 09:16 UTC, yeongunheo commented on doonut-app-external-api/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
저도 세훈님 의견에 동의해요!  
`doonut-app-external-api`는 jpa를 직접적으로 의존하면 안될 것 같아요.

2023-11-04 09:16 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/controller/KakaoOauthController.kt
> +    @PostMapping("login/{oauthType}")
저도 getKakaoSelctedUserInfo API는 프론트엔드에서 불필요하기에 제거하는게 좋을 것 같네요.

2023-11-04 09:16 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/controller/KakaoOauthController.kt
>  @RequestMapping("/kakao")
저도 oauthType을 인자로 받는거라면 /kakao prefix는 제거해도 좋을 것 같네요.

2023-11-04 09:16 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/controller/KakaoOauthController.kt
> +    fun signUp(@PathVariable oauthType: OauthType, @RequestBody tokenRequest: KakaoTokenRequest): Member? {
메서드명을 `login`으로 바꾸는건 어떨까요?  
이미 있는 회원이면 기존 값 조회, 새로운 회원이면 회원가입은 내부 로직이라서 `login에 성공한다`가 메서드가 갖는 책임이라고 생각했어요.

2023-11-04 09:16 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/service/KakaoOauthLoginService.kt
> +    fun kakaoLoginPreventDuplication(tokenRequest: KakaoTokenRequest, oauthType: OauthType): Member? {
반환하는 Member 객체가 null이 아님이 보장되니까 ?을 제거해도 좋을 것 같아요.  
```suggestion
    fun kakaoLoginPreventDuplication(tokenRequest: KakaoTokenRequest, oauthType: OauthType): Member {
```

2023-11-04 09:16 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/service/KakaoOauthLoginService.kt
> +    fun kakaoSignUpNewMember(tokenRequest: KakaoTokenRequest, oauthType: OauthType): Member? {
여기도 ?을 제거해도 좋을 것 같아요.  
```suggestion
    fun kakaoSignUpNewMember(tokenRequest: KakaoTokenRequest, oauthType: OauthType): Member {
```

2023-11-04 09:16 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/service/KakaoOauthLoginService.kt
> +    fun kakaoSignUpNewMember(tokenRequest: KakaoTokenRequest, oauthType: OauthType): Member? {
oauthTyped을 인자로 받으니 클래스명, 메서드명에서 kakao를 제거해보는건 어떨까요?

2023-11-04 09:16 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/service/KakaoOauthLoginService.kt
> +    fun kakaoLoginPreventDuplication(tokenRequest: KakaoTokenRequest, oauthType: OauthType): Member? {
메서드명에 PreventDuplication을 제거해도 좋을 것 같아요.

2023-11-04 09:16 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/dto/KakaoInfoResponse.kt
> +    val id: String?,
id가 null이면 그냥 에러가 발생하도록 하는게 좋을 것 같아요.

```suggestion
    // TODO: 이거 long으로 바꿔야함
    val id: String,
```

2023-11-04 09:16 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/dto/KakaoInfoResponse.kt
> +    val id: String?,
궁금한게 이건 왜 String이 아닌 long으로 바꿔야하나요?

2023-11-04 09:16 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/service/KakaoOauthLoginService.kt
> +            ?: kakaoSignUpNewMember(tokenRequest, oauthType)
엘비스 연산자를 적절하게 사용하셨네요 💯

2023-11-04 10:39 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/dto/KakaoInfoResponse.kt
> +    val id: String?,
이 부분은 카카오에서 받아온 **ouathId**가 **Long**으로 넘어옵니다. 일단은 **member record**의 **oauthId**가 **string**이라서 **KakaoInfoResponse DTO**도 **string**으로 만들두었습니다. **string**여도 문제는 안생기긴 하는데 제가 모르는 부분에서 문제가 생길 거 같아서 넘어온 타입을 맞춰주는 게 맞다고 생각했습니다!!

2023-11-04 11:22 UTC, jickDo commented on doonut-app-external-api/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
궁금한점이 생겨서 질문 남깁니다!!
이 의존성은 `@Transactional`을 코틀린 서비스단에서 사용하는게 맞는지 아닌지 고민을 하다가 넣었어요...
 `@Transactional`이 `data-jpa` 와 의존성이 있는 상황인데, **db**와 관련한 기능을 수행하는 서비스 단은 **core** 쪽 자바의 서비스 잖아요? 
 **external-api** 쪽 코틀린의 서비스 단에서 트랜잭션없이 자바 서비스에 접근했을 때 문제가 생길지 안생길지 제가 생각했을 때는 미지수에요...
 그래서 이렇게 질문을 남기게 되었습니다 😅

2023-11-04 11:28 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/controller/KakaoOauthController.kt
> +    @PostMapping("login/{oauthType}")
생각해보니 그렇네요..! 좋은 피드백 감사드립니다 ☺️

2023-11-04 11:42 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/service/KakaoOauthLoginService.kt
> +    fun kakaoSignUpNewMember(tokenRequest: KakaoTokenRequest, oauthType: OauthType): Member? {
고민을 했던 부분이 oauthType을 받고 카카오와 애플 처리 기능을 통합하는게 깔끔하다고 생각했는데,  문제가 애플 oauth의 처리방식을 정확히 아는게 아닌 상황에서 둘의 기능을 통합하는게 힘들었습니다.. 카카오도 한번 만들어두면 나중에 리팩토링을 해야하는 비용이 생기니 이부분은 어떻게 처리 해야할지 여쭈어 보고 싶었습니다!!

2023-11-04 11:45 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/controller/KakaoOauthController.kt
> +    fun signUp(@PathVariable oauthType: OauthType, @RequestBody tokenRequest: KakaoTokenRequest): Member? {
오... 진짜 그렇네요
좋은 피드백감사드립니다. 메서드명 붙일때 고민을 좀더 해보면서 붙여야 겠네요

2023-11-05 12:13 UTC, yeongunheo commented on doonut-app-external-api/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
코틀린 서비스 단에서 repository를 직접적으로 의존하려는게 아닌, `@Transactional`을 import하기 위해서 넣으셨던 거군요!  
그렇다면 이 의존성을 추가해도 됩니다.  

> external-api 쪽 코틀린의 서비스 단에서 트랜잭션없이 자바 서비스에 접근했을 때 문제가 생길지 안생길지 제가 생각했을 때는 미지수에요...  

자바로 구성된 BusinessService 단에는 제가 `@Transactional`을 모두 붙여두긴 했습니다! 그래서 코틀린 서비스에 `@Transactional`을 선언하지 않아도 문제없이 동작하긴 합니다. 저희가 이렇게 멀티모듈로 구성한 이유 중 하나가 바로 core 쪽 서비스에만 트랜잭션을 걸어서 트랜잭션을 짧게 가져가려는 것도 있습니다.

2023-11-05 12:15 UTC, yeongunheo commented on doonut-app-external-api/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
코틀린 서비스에 `@Transactional`을 붙임으로써 얻는 장점은 같은 트랜잭션 내에서 읽기와 쓰기가 이뤄지기 때문에 좀 더 안전하다는 장점이 있는 걸로 알고 있어요. 대신 트랜잭션 길이가 길어짐으로써 잃는 성능이 트레이드 오프라고 생각합니다.  

external-api 쪽 코틀린의 서비스에는 트랜잭션을 걸지 않고 core 쪽 자바 서비스에만 트랜잭션을 거는 방향으로 가면 어떨까 합니다.

2023-11-05 12:17 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/service/KakaoOauthLoginService.kt
> +    fun kakaoSignUpNewMember(tokenRequest: KakaoTokenRequest, oauthType: OauthType): Member? {
이 부분은 저도 애플 로그인을 아직 구현해보지 못했기 때문에, 어떤 방식이 옳다는 확답을 드릴 순 없겠네요ㅠ

2023-11-05 12:20 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/dto/KakaoInfoResponse.kt
> +    val id: String?,
아하 그렇다면 Long 가도 상관없을 것 같네요.  
전 카카오의 정책 변경에 따라 oauthId가 Long에서 String으로 바뀌게 되면 저희도 바꾸어야 하기에 안전하게 String으로 저장하는게 낫지 않을까? 생각했습니다ㅎ

2023-11-05 12:22 UTC, yeongunheo approved these changes
고생하셨습니다!

2023-11-05 12:22 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/service/KakaoOauthLoginService.kt
> +    fun Login(tokenRequest: KakaoTokenRequest, oauthType: OauthType): Member? {
메서드명은 소문자로 시작해야할 것 같아요!

2023-11-05 12:22 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/service/KakaoOauthLoginService.kt
> +    fun SignUpNewMember(tokenRequest: KakaoTokenRequest, oauthType: OauthType): Member {
위 코멘트와 동일합니다!

2023-11-06 03:54 UTC, oereo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/kakao/service/KakaoOauthLoginService.kt
> +    fun kakaoSignUpNewMember(tokenRequest: KakaoTokenRequest, oauthType: OauthType): Member? {
그런 고민이 있으셨군요!!
처리 기능이 통합되는 것을 지향하신다면은 일단 method 자체를 kakao~ prefix를 붙이면 살짝 안될 것 같아요!
만약 통합하는 방향으로 로직을 설계한다고 하면 약간의 오버스펙이 될 수 있지만 전략패턴을 적용해서 구현하는 것도 좋을 것 같아요! interface를 만들고 signupNewMember 라는 method를 선언한 뒤에 구현체를 만드는 방향은 어떠신가요? 그렇게 되면 oauthType이 사용될 수 있는 설계가 될 것 같습니다!

2023-11-06 03:56 UTC, oereo approved these changes

2023-11-06 13:13 UTC, yeongunheo approved these changes
고생하셨습니다!  
이대로 머지해도 될 것 같아서 코멘트만 하나 남겨놓았어요

2023-11-06 13:13 UTC, yeongunheo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/common/OauthProvider.kt
> +    abstract fun getUserInfo(tokenRequest: TokenRequest): U
인터페이스가 아닌 추상클래스로 선언한 이유는 무엇인가요?

2023-11-06 15:36 UTC, jickDo commented on doonut-app-external-api/src/main/kotlin/com/doonutmate/oauth/common/OauthProvider.kt
> +    abstract fun getUserInfo(tokenRequest: TokenRequest): U
저는 `oauth` 아래 `kakkoOauth` 와 `appleOauth`로 분기되는 부모 자식 관계로 생각했어요. `인터페이스`는 공통부분이 없는 것들에 공통적인 기능을 모아놓은 부분이라면, `추상 클래스`는 공통되는 부모 아래 뻗어나가는 것들이라는 점에 `추상 클래스`로 구현하게 되었습니다! 혹시 제가 잘못 이해하거나, 이 부분은 `인터페이스`로 구현하는 게 더 좋은 점이 있다면 말씀해주세요!!

아래는 제가 참고했던 기술 블로그입니다.

https://inpa.tistory.com/entry/JAVA-%E2%98%95-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4-vs-%EC%B6%94%EC%83%81%ED%81%B4%EB%9E%98%EC%8A%A4-%EC%B0%A8%EC%9D%B4%EC%A0%90-%EC%99%84%EB%B2%BD-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0

2023-11-06 15:36 UTC, merged